# This file was generated by liblab | https://liblab.com/

from ups_0auth_client_credentials import Ups0authClientCredentials, Environment
from ups_0auth_client_credentials.models import CreateTokenRequest

sdk = Ups0authClientCredentials(
    username="YOUR_USERNAME",
    password="YOUR_PASSWORD",
    base_url=Environment.DEFAULT.value,
)

request_body = CreateTokenRequest(grant_type="client_credentials")

result = sdk.security.create_token(
    request_body=request_body, x_merchant_id="x-merchant-id"
)

print(result)
